name: Deploy to server

on:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Retrieving modified files
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_ADDRESS }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script_stop: true
                  script: |
                      cd ${{ secrets.API_PATH }}
                      git fetch --all
                      git checkout master
                      git reset --hard origin/master
                      git pull
            - name: Build
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_ADDRESS }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script_stop: true
                  script: |
                      cd ${{ secrets.API_PATH }}
                      rm -rf ./dist/
                      yarn
                      npm run build
            - name: Start
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_ADDRESS }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{ secrets.SERVER_USERNAME }}
                  password: ${{ secrets.SERVER_PASSWORD }}
                  script_stop: true
                  script: |
                      cd ${{ secrets.API_PATH }}
                      pm2 stop ./dist/main.js > /dev/null
                      pm2 start ./dist/main.js --name="API" > /dev/null
            - name: Final
              run: echo "Succesfully deployed"
